#!/bin/bash

export AUR_PACKAGES=(
    #Desktop apps
#   visual-studio-code-bin
    rider
    pwvucontrol

    #Misc
    xdg-terminal-exec-git

    #CLI utils
    byedpi
    
    #Java
    jdk-openjdk-wakefield
)
